version: '2'
services:
  surveys-api:
    container_name: surveys-api
    build:
      context: .
      target: debug
    command: "dotnet run"
    working_dir: /app
    volumes:
      - ./apps/surveys-api:/app/
    networks:
      - surveys-network
    ports:
      - 5001:5001
      - 5000:5000
  surveys-ui:
    container_name: surveys-ui
    build:
      context: .
      target: angular
    command:  "ng serve --host=0.0.0.0 --disable-host-check"
    working_dir: /app/surveys-ui-angular
    volumes:
      - ./apps/surveys-ui-angular:/app/
    networks:
      - surveys-network
    ports:
      - 4200:4200
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
        - surveys-network
    depends_on:
      postgres:
        condition: service_started
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=anysecret"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
        - surveys-network
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=anysecret
      # - KEYCLOAK_IMPORT=/tmp/realm-test.json
    volumes:
      - ./:/temp
      # - ./infra/keycloak/realm-test.json:/tmp/realm-test.json
    # command: ["-Dkeycloak.profile.feature.upload_scripts=enabled"]
    depends_on:
      - postgres
    networks:
      - surveys-network

networks:
  surveys-network:
    driver: bridge
